# -*- coding: utf-8 -*-
"""RAG application GeekForGeeks ChatBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SzTufDyzF9j16RI3PWzD3JEOO_mPbGZ7
"""

!pip install langchain_community langchainhub chromadb langchain langchain-openai

from google.colab import userdata
import os
os.environ['GOOGLE_API_KEY']=userdata.get('GOOGLE_API_KEY')

from langchain_community.document_loaders import WebBaseLoader

loader = WebBaseLoader(web_paths=["https://www.geeksforgeeks.org/web-development/"])
docs=loader.load()

from langchain.text_splitter import RecursiveCharacterTextSplitter
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
splits = text_splitter.split_documents(docs)

print(splits[0])

print(len(splits))

# STEP 5: Create Vectorstore using Gemini Embeddings
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain.vectorstores import Chroma

embeddings = GoogleGenerativeAIEmbeddings(model="models/embedding-001")
vectorstore = Chroma.from_documents(documents=splits, embedding=embeddings)
retriever = vectorstore.as_retriever()

print(vectorstore._collection.count())

print(vectorstore._collection.get())

print("Collection 1: ",vectorstore._collection.get(ids=['85eb9e8c-e911-4c03-a03f-899dc449f370'],include=["embeddings","documents"]))

retriever= vectorstore.as_retriever()

from langchain import hub
prompt=hub.pull("rlm/rag-prompt")

from langchain_google_genai import ChatGoogleGenerativeAI
llm = ChatGoogleGenerativeAI(model="gemini-1.5-flash-latest", temperature=0.2)

from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

def format_docs(docs):
  return '\n'.join(doc.page_content for doc in docs)

llm.invoke("what is rag?")

rag_chain = ({"context":retriever | format_docs,"question":RunnablePassthrough()}
             |prompt
             |llm
             |StrOutputParser())

query = input("Enter your Query: ")
rag_chain.invoke(query)

!pip install langchain-google-genai